# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserLogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroSensor',
            fields=[
                ('macro_id', models.AutoField(primary_key=True, serialize=False)),
                ('read_time', models.DateField(auto_now=True)),
                ('Temperature', models.FloatField(null=True)),
                ('Humidity', models.FloatField(null=True)),
                ('WaterLevel', models.FloatField(null=True)),
                ('Rain', models.FloatField(null=True)),
                ('Latitude', models.FloatField(null=True)),
                ('Longitude', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MicroSensor',
            fields=[
                ('micro_id', models.AutoField(primary_key=True, serialize=False)),
                ('read_time', models.DateField(auto_now=True)),
                ('SoilMoisture', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('Latitude', models.FloatField(null=True)),
                ('Longitude', models.FloatField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserLogin.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='microsensor',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensors.Plant'),
        ),
    ]
